import "../globals.css";

import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import Context from "../contextApi/Context";
import ProfileSIdebar from "./ProfileComponents/ProfileSIdebar";
import ProfileInfo from "./ProfileComponents/ProfileInfo";
import { getDataHandler } from "../actions/users/getData";
import { getMyProfileInfo } from "../constans/constans";

export const metadata = {
    title: "Profile Online-exam",
    description: "Generated by create next app",
};

export default async function ProfileLayout({ children }) {
    const api = getMyProfileInfo;
    const { status, result } = await getDataHandler(api);

    if (status && status !== 200) {
        return <NotFound page={"User"} />
    }
 

    return (
        <html lang="en">
            <body className="bg-gray-200 h-screen overflow-hidden text-gray-900">
                <Context>
                    <ToastContainer />

                    <div className="flex flex-col md:flex-row h-screen">
                        {/* Sidebar */}
                        <aside className="w-full md:w-64 bg-gray-800 text-white h-auto md:h-full flex flex-col items-center p-5">
                            {/* Profile Section */}
                            <div className=" w-full flex flex-col items-center mb-10">
                                <ProfileInfo profileInfo={result} />
                            </div>
                            <ProfileSIdebar />
                            <div className="h-10"></div>
                        </aside>

                        {/* Main Content */}
                        <main className="flex-1 p-5 md:p-10 bg-white rounded-md overflow-y-auto">
                            {children}
                            <div className="h-10"></div>
                        </main>
                    </div>
                </Context>
            </body>
        </html>
    );
}
